# Generated by Django 6.0 on 2026-02-25 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_skill_remove_job_posted_at_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
